---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[openvpn_okta_test]
    attributes:
      openvpn_okta:
        url: example.com
        token: abc123
  - name: remove
    run_list:
      - recipe[openvpn_okta_test::remove]
